# Generated by Django 4.0.2 on 2022-02-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='no image for this post', upload_to='featured_image/%Y/%m/%d/'),
        ),
    ]
