# Generated by Django 4.0.2 on 2022-02-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.CharField(default='HOD', max_length=250),
        ),
    ]
